### ISSUE TITLE
The project not compile

### ISSUE THREAD

**Issue by cgnunezbantics** [sohanKumawat/springboot-angular2-jwt#1]
Hello, Good work. I test your project and  give this error, files missing:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project msgai-ui-application: Compilation failure: Compilation failure:
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/process/DataMarshaller.java:[8,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/process/MarshallerHelper.java:[6,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/process/MarshallerHelper.java:[13,66] cannot find symbol
[ERROR] symbol:   class GetReportsResponse
[ERROR] location: class ai.msg.adapter.process.MarshallerHelper
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/service/ReportResponseService.java:[11,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/service/ReportResponseService.java:[16,17] cannot find symbol
[ERROR] symbol:   class GetReportsResponse
[ERROR] location: class ai.msg.adapter.service.ReportResponseService
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/adapter/service/ReportResponseService.java:[20,32] cannot find symbol
[ERROR] symbol:   class GetReportsResponse
[ERROR] location: class ai.msg.adapter.service.ReportResponseService
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/modules/controller/AnalyticsController.java:[12,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/modules/controller/AnalyticsController.java:[13,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/modules/controller/AnalyticsController.java:[14,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/modules/controller/AnalyticsController.java:[15,28] package ai.msg.reports.model does not exist
[ERROR] /home/cgnunez/gitext/springboot-angular2-jwt/src/main/java/ai/msg/modules/controller/AnalyticsController.java:[16,28] package ai.msg.reports.model does not exist

Thanks

**Comment by sohanKumawat** [comment]
Hi ,
I have checkout updated code into another branch, Look on the same.

branch name is - angular2-jwtsecurity-springmvc

**Comment by cgnunezbantics** [comment]
Thanks.
